inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/update'
    - 'vendor/**/*'
    - 'node_modules/**/*'

  NewCops: enable

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
